# Generated by Django 4.0.5 on 2022-06-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
